/**
 * Emojis para as categorias de comandos
 * A ordem das chaves define a ordem de apresentação das categorias
 */
const CATEGORY_EMOJIS = {
  "geral": "📃",
  "grupo": "👥",
  "utilidades": "🛠️",
  "midia": "📱",
  "ia": "🤖",
  "downloaders": "📤",
  "jogos": "🎮",
  "cultura": "🍿",
  "áudio": "🔈",
  "tts": "🗣",
  "busca": "🔎",
  "listas": "📜",
  "arquivos": "📂",
  "general": "🖨️",
  "diversao": "🎮",
  "info": "ℹ️",
  "imagens": "🖼️",
  "resto": "❓",
};

/**
 * Ordem personalizada para comandos por nome
 * Os comandos não listados aparecem depois na ordem original
 */
const COMMAND_ORDER = [
	"cmd",
	"cmd-grupo",
	"cmd-gerenciamento",
	"cmd-g",
	"doar",
	"convite",
	"grupao",
	"avisos",
	"codigo",
	"faladores",
	"apelido",
	"clima",
	"news",
	"apagar",
	"atencao",
	"ignorar",
	"stt",
	"traduzir",
	"lembretes",
	"lembrar",
	"l-cancelar",
	"f",
	"fig",
	"figurinha",
	"s",
	"sticker",
	"sbg, stickerbg",
	"removebg",
	"distort",
	"neon",
	"oil",
	"pixelate",
	"sketch",
	"ai",
	"imagine",
	"resumo",
	"interagir",
	"yt",
	"sr",
	"anonimo",
	"roletarussa",
	"roletaranking",
	"pescar",
	"pesca-iscas",
	"pesca-ranking",
	"pescados",
	"meus-pescados",
	"pesca-lendas",
	"pinto",
	"pinto-ranking",
	"roll",
	"d10",
	"lol",
	"valorant",
	"wr",
	"anime",
	"imdb",
	"volume",
	"getaudio",
	"getvoice",
	"tts",
	"tts-mulher",
	"tts-homem",
	"buscar",
	"buscar-img",
	"gif",
	"wiki",
	"lastfm",
	"listas",
	"lc",
	"lct",
	"ld",
	"le",
	"ls",
	"lt",
	"lr",
	"pastas",
	"p-enviar",
	"p-criar",
	"p-baixar",
	"p-excluir",
	"ajuda",
	"info",
	"setName",
	"setPrefixo",
	"addCmd",
	"delCmd",
	"enableCmd",
	"disableCmd",
	"cmdReact",
	"cmdStartReact",
	"addCmdReply",
	"variaveis",
	"setBemvindo",
	"setDespedida",
	"apelido",
	"ignorar",
	"mute",
	"pausar",
	"autoStt",
	"setTempoRoleta",
	"filtro-palavra",
	"filtro-links",
	"filtro-nsfw",
	"filtro-pessoa",
	"interagir",
	"interagir-cd",
	"interagir-chance",
	"customAdmin",
	"twitch-canal",
	"twitch-mudarTitulo",
	"twitch-usarIA",
	"twitch-titulo-on",
	"twitch-titulo-off",
	"twitch-midia-on",
	"twitch-midia-off",
	"kick-canal",
	"kick-mudarTitulo",
	"kick-usarIA",
	"kick-titulo-on",
	"kick-titulo-off",
	"kick-midia-on",
	"kick-midia-off",
	"youtube-canal",
	"youtube-mudarTitulo",
	"youtube-usarIA",
	"youtube-titulo-on",
	"youtube-titulo-off",
	"youtube-midia-on",
	"youtube-midia-off"
];

module.exports = { COMMAND_ORDER, CATEGORY_EMOJIS }